theme: jekyll-theme-cayman
title: CoqHammer
description: Proof Automation for Dependent Type Theory

github:
  repository_url: "https://github.com/lukaszcz/coqhammer"

show_downloads: true

navbar-links:
  View on github: "https://github.com/lukaszcz/coqhammer"
  Download: "https://github.com/lukaszcz/coqhammer/releases"
