theme: jekyll-theme-leap-day
title: CoqHammer
description: Proof Automation for Dependent Type Theory

navbar-links:
  View on github: "https://github.com/lukaszcz/coqhammer"
  Download: "https://github.com/lukaszcz/coqhammer/releases"
