theme: jekyll-theme-cayman
title: CoqHammer
description: Proof Automation for Dependent Type Theory

show_downloads: false

github:
  is_project_page: true
  repository_url: "https://github.com/lukaszcz/coqhammer"
  repository_name: CoqHammer
  owner_url: "http://www.mimuw.edu.pl/~lukaszcz"
  owner_name: "Lukasz Czajka"
