theme: jekyll-theme-leap-day
title: CoqHammer
description: Proof Automation for Dependent Type Theory

is_project_page: true
show_downloads: false

github:
  repository_url: "https://github.com/lukaszcz/coqhammer"
